version: '3.8'

services:
  # Zookeeper Service (required by Kafka)
  phoenix-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: phoenix-commerce-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - phoenix-zookeeper-data:/var/lib/zookeeper/data
      - phoenix-zookeeper-log:/var/lib/zookeeper/log
    networks:
      - phoenix-commerce-network

  # Kafka Service
  phoenix-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: phoenix-commerce-kafka
    depends_on:
      - phoenix-zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: phoenix-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://phoenix-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - phoenix-kafka-data:/var/lib/kafka/data
    networks:
      - phoenix-commerce-network

  # Kafka UI (optional but helpful)
  phoenix-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: phoenix-commerce-kafka-ui
    depends_on:
      - phoenix-kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: phoenix
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: phoenix-kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: phoenix-zookeeper:2181
    networks:
      - phoenix-commerce-network

  # MongoDB Service
  phoenix-mongodb:
    image: mongo:latest
    container_name: phoenix-commerce-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - phoenix-mongodb-data:/data/db
    networks:
      - phoenix-commerce-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Service
  phoenix-redis:
    image: redis:latest
    container_name: phoenix-commerce-redis
    ports:
      - "6379:6379"
    volumes:
      - phoenix-redis-data:/data
    networks:
      - phoenix-commerce-network

  # Redis Commander (optional but helpful)
  phoenix-redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: phoenix-commerce-redis-commander
    depends_on:
      - phoenix-redis
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: phoenix:phoenix-redis:6379
    networks:
      - phoenix-commerce-network

  # Postgres for Keycloak
  postgres:
    image: postgres:15
    container_name: phoenix-commerce-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - phoenix-commerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: phoenix-commerce-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - phoenix-commerce-network

networks:
  phoenix-commerce-network:
    driver: bridge
    name: phoenix-commerce-network

volumes:
  phoenix-zookeeper-data:
    name: phoenix-commerce-zookeeper-data
  phoenix-zookeeper-log:
    name: phoenix-commerce-zookeeper-log
  phoenix-kafka-data:
    name: phoenix-commerce-kafka-data
  phoenix-mongodb-data:
    name: phoenix-commerce-mongodb-data
  phoenix-redis-data:
    name: phoenix-commerce-redis-data
  postgres_data:
    name: phoenix-commerce-postgres-data